import Link from 'next/link';
import { ArrowRight, BadgePercent, CalendarCheck, Camera, Check, Clock3, Droplets, Images, MapPin, MessageCircle, ShieldCheck, Sparkles, Truck, Zap } from 'lucide-react';
import FeaturedCarousel from './FeaturedCarousel';
import { CORE_SERVICES, HEAVY_VEHICLE_PRICE, addOnPriceLabel, priceForPackage } from '../lib/pricing';

export default function HomeSections() {
  const extras = CORE_SERVICES.filter((service) => service.selectable);
  return (
    <>
      <section id="home" className="home-hero">
        <div className="mx-auto grid max-w-6xl items-center gap-10 px-5 py-16 md:grid-cols-[1.05fr_.95fr] md:py-24">
          <div><span className="font-label text-xs text-[var(--gold-400)]">DOORSTEP CAR CARE · KURAVILANGADU</span><h1 className="font-display mt-4 text-4xl leading-tight text-[var(--cream-50)] sm:text-5xl md:text-6xl">A cleaner car, without leaving home.</h1><p className="font-body mt-5 max-w-xl text-base leading-7 text-[var(--teal-100)] md:text-lg">Complete exterior and interior car care at your doorstep. We bring our own water, power and equipment.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/book" className="btn-primary inline-flex items-center gap-2">Book a wash <ArrowRight size={18}/></Link><Link href="/services" className="btn-outline inline-flex items-center">View services</Link></div><div className="mt-7 flex flex-wrap gap-3 text-sm text-[var(--teal-100)]"><span className="hero-pill"><Clock3 size={15}/> 8 AM–9 PM</span><span className="hero-pill"><MapPin size={15}/> Around 20 km</span><span className="hero-pill"><MessageCircle size={15}/> WhatsApp confirmation</span></div></div>
          <div className="home-hero-media"><div className="home-hero-badge"><Droplets size={18}/> Own water <span>+</span> <Zap size={18}/> Own power</div>{/* eslint-disable-next-line @next/next/no-img-element */}<img src="/gallery/foam-wash-1.webp" alt="Aqua Haul doorstep foam wash" /></div>
        </div>
      </section>

      <section className="home-section bg-[var(--cream-50)] px-4 py-14 sm:px-6 md:py-20"><div className="mx-auto grid max-w-6xl gap-4 md:grid-cols-3"><Quick href="/book" icon={CalendarCheck} title="Book a Wash" text="Choose a service, map location and available slot."/><Quick href="/services" icon={Sparkles} title="Explore Services" text="See current prices, inclusions and add-ons."/><Quick href="/gallery" icon={Camera} title="View Our Work" text="Browse real photos from recent jobs."/></div></section>

      <section className="home-section bg-[var(--cream-100)] px-4 py-16 sm:px-6 md:py-24"><div className="mx-auto max-w-6xl"><div className="mx-auto max-w-2xl text-center"><span className="font-label text-xs text-[var(--terracotta-600)]">FEATURED PACKAGE</span><h2 className="font-display mt-3 text-3xl text-[var(--teal-900)] md:text-5xl">Complete Care Wash</h2><p className="font-body mt-3 text-[var(--ink-muted)]">Foam Wash and Interior Detailing together in one clear package.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><div className="home-package-card"><div><span className="font-label text-[10px] text-[var(--terracotta-600)]">INCLUDED</span><h3 className="font-display mt-2 text-3xl text-[var(--teal-900)]">Exterior + interior care</h3><div className="mt-5 grid gap-3 sm:grid-cols-2"><PackageLine text="Foam Wash"/><PackageLine text="Interior Detailing"/><PackageLine text="We bring our own water"/><PackageLine text="We bring our own power"/></div></div><div className="home-price-box"><div><span>5-Seater</span><strong>₹{priceForPackage('5-Seater')}</strong></div><div><span>7-Seater</span><strong>₹{priceForPackage('7-Seater')}</strong></div><Link href="/book" className="btn-primary mt-4 block text-center">Book Complete Care</Link></div></div><div className="home-heavy-card"><Truck size={30}/><span className="font-label mt-6 text-[10px] text-[var(--gold-400)]">LARGER VEHICLES</span><h3 className="font-display mt-2 text-2xl">Heavy Vehicle Wash</h3><strong className="font-display mt-5 block text-4xl">From ₹{HEAVY_VEHICLE_PRICE}</strong><Link href="/services" className="mt-6 inline-flex items-center gap-2 font-bold text-[var(--gold-400)]">View details <ArrowRight size={17}/></Link></div></div><div className="mt-6 flex flex-wrap justify-center gap-2">{extras.map((service) => <span key={service.id} className="addon-chip">{service.name} · {addOnPriceLabel(service.id)}</span>)}</div></div></section>

      <section className="home-section bg-[var(--cream-100)] px-4 pb-16 sm:px-6 md:pb-24"><div className="mx-auto max-w-6xl"><div className="offer-card"><span className="offer-icon"><BadgePercent size={24}/></span><div><span className="font-label text-[10px] text-[var(--gold-400)]">GROUP WASH OFFER</span><h2 className="font-display mt-1 text-2xl md:text-3xl">3 cars together? Save 20–30%</h2><p className="font-body mt-2 max-w-3xl text-sm leading-6 text-[var(--teal-100)]">Get 20–30% off when 3 cars from your family or friends are at the same location, or within 3 km of each other. Final discount depends on the vehicles and services selected.</p></div><Link href="/book" className="offer-link">Book 3 cars <ArrowRight size={17}/></Link></div></div></section>

      <FeaturedCarousel />

      <section className="home-section bg-white px-4 py-16 sm:px-6 md:py-24"><div className="mx-auto max-w-6xl"><div className="text-center"><span className="font-label text-xs text-[var(--terracotta-600)]">HOW IT WORKS</span><h2 className="font-display mt-3 text-3xl text-[var(--teal-900)] md:text-5xl">Four simple steps</h2></div><div className="mt-10 grid gap-4 md:grid-cols-4">{['Choose your service','Enter your location','Select an available slot','We arrive at your doorstep'].map((text,index)=><div key={text} className="process-card"><span>{index+1}</span><h3>{text}</h3></div>)}</div></div></section>

      <section className="home-section bg-[var(--cream-50)] px-4 py-16 sm:px-6 md:py-24"><div className="mx-auto grid max-w-6xl gap-8 lg:grid-cols-2"><div><span className="font-label text-xs text-[var(--terracotta-600)]">WHY AQUA HAUL</span><h2 className="font-display mt-3 text-3xl text-[var(--teal-900)] md:text-5xl">Local, clear and convenient</h2><div className="mt-7 grid gap-3 sm:grid-cols-2"><Trust icon={Droplets} text="Own water and equipment"/><Trust icon={ShieldCheck} text="Clear upfront pricing"/><Trust icon={MapPin} text="Route-aware scheduling"/><Trust icon={MessageCircle} text="WhatsApp confirmation"/></div></div><div className="service-area-card"><MapPin size={32}/><h3 className="font-display mt-4 text-3xl">Serving Kuravilangadu and nearby areas</h3><p className="font-body mt-3 leading-7 text-[var(--teal-100)]">Enter your map location during booking to check availability within our normal service area of approximately 20 km.</p><Link href="/book" className="mt-6 inline-flex items-center gap-2 font-bold text-[var(--gold-400)]">Check your location <ArrowRight size={17}/></Link></div></div></section>

      <section className="home-cta px-4 py-16 sm:px-6 md:py-20"><div className="mx-auto max-w-4xl text-center"><Images className="mx-auto text-[var(--gold-400)]" size={34}/><h2 className="font-display mt-4 text-3xl text-white md:text-5xl">Ready for a cleaner car?</h2><p className="font-body mx-auto mt-3 max-w-xl text-[var(--teal-100)]">Choose your service and reserve one of the available appointment slots.</p><Link href="/book" className="btn-primary mt-7 inline-flex items-center gap-2">Book Now <ArrowRight size={18}/></Link></div></section>
    </>
  );
}

function Quick({href,icon:Icon,title,text}){return <Link href={href} className="quick-card"><span><Icon size={23}/></span><div><h2>{title}</h2><p>{text}</p></div><ArrowRight className="ml-auto" size={19}/></Link>}
function PackageLine({text}){return <p className="font-body flex items-center gap-2 font-bold text-[var(--teal-900)]"><Check size={17}/>{text}</p>}
function Trust({icon:Icon,text}){return <div className="trust-card"><Icon size={21}/><span>{text}</span></div>}
